version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: fortune
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fortune_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
